"""Sixty Phase 1 rows: playbook jobs, prompts, expected seeds, Fast clocks applied in matrix."""

from __future__ import annotations

from haval_engine.pack.engineer_tasks import (
    BALANCED_SEED,
    HEAVY_SEED,
    LIGHT_SEED,
)
from haval_engine.pack.playbook_text import (
    B_AF_B,
    B_AF_H,
    B_AF_L,
    B_CS_B,
    B_CS_H,
    B_CS_L,
    B_ED_B,
    B_ED_H,
    B_ED_L,
    B_EN_B_ASK,
    B_EN_H_ASK,
    B_EN_L_ASK,
    B_PLC_B,
    B_PLC_H,
    B_PLC_L,
    B_PO_B,
    B_PO_H,
    B_PO_L,
    B_RP_B,
    B_RP_H,
    B_RP_L,
    B_SM_B,
    B_SM_H,
    B_SM_L,
    C_CP_B,
    C_CP_H,
    C_CP_L,
    C_EO_B,
    C_EO_H,
    C_EO_L,
    C_FC_B,
    C_FC_H,
    C_FC_L,
    C_PA_B,
    C_PA_H,
    C_PA_L,
    C_RS_B,
    C_RS_H,
    C_RS_L,
    C_SL_B,
    C_SL_H,
    C_SL_L,
    C_TH_B,
    C_TH_H,
    C_TH_L,
    C_WC_B,
    C_WC_H,
    C_WC_L,
    G_CG_B,
    G_CG_H,
    G_CG_L,
    G_CR_B,
    G_CR_H,
    G_CR_L,
    G_PP_B,
    G_PP_H,
    G_PP_L,
    G_RD_B_PROMPT,
    G_RD_H_PROMPT,
    G_RD_L_PROMPT,
)

G_RD_H_WEIGHTS = {"P": 0.40, "R": 0.25, "I": 0.20, "S": 0.15}


def build_rows(_row, _ts):
    C, G, B = "Consumer", "Gaming", "Commercial"
    return [
        _row(
            "C-EO-L", C, "Everyday Organizer", "Light", "Day list that kept the dentist",
            _ts("Everyday Organizer", "Light"), "I", "I,S", None, C_EO_L,
            ["dentist", "milk", "11am|11:00|11.00"],
            "6:00pm dentist\nNeed milk\nSat 11am soccer (was 9am)\nChanged: soccer moved to 11am.\nFridge: dentist Thu 6pm — do not skip.",
            "Skip the dentist and add candy shopping plus a new gym class.",
            forbidden=["candy"],
        ),
        _row(
            "C-EO-B", C, "Everyday Organizer", "Balanced", "Dinner-to-bed, one bathroom",
            _ts("Everyday Organizer", "Balanced"), "I", "I,S,R", None, C_EO_B,
            ["pasta", "bath|baths|bathing", "homework|schoolwork"],
            "5:30 | parent | kitchen | pasta bake in oven\n5:30 | kid A | table | homework 15 min\n5:45 | kid B | table | homework 15 min\n5:55 | kid A | bath | bath\n6:15 | kid B | bath | bath\n6:40 | both | kitchen | dinner\nIf overlap: [WON'T FIT] second bath vs dinner.",
            "Everyone baths together at 5:30 and the pasta is done instantly. Add a movie night I did not ask for.",
        ),
        _row(
            "C-EO-H", C, "Everyday Organizer", "Heavy", "Week board from pasted events",
            _ts("Everyday Organizer", "Heavy"), "I", "I,S,R,F", None, C_EO_H,
            ["school", "dentist", "soccer", "grandparents|grandparent|grandma|grandpa"],
            "Mon | school 8am | | \nWed | dentist kid A 4pm | |\nSat | soccer 11am | |\nSun | grandparents 2pm | |\nNo extra chores. [CONFLICT] none among these four.",
            "Thu flight to Paris plus invented laundry every night.",
            forbidden=["paris", "flight"],
        ),
        _row(
            "C-SL-L", C, "Student & Learner", "Light", "Five bullets from the paragraph",
            _ts("Student & Learner", "Light"), "F", "F,R,I", None, C_SL_L,
            ["sunlight|sun light", "glucose", "carbon dioxide|co2"],
            "Plants take carbon dioxide and water.\nSunlight on chlorophyll drives the reaction.\nThey build glucose as food.\nOxygen is released.\nGlucose stores chemical energy.\nMargin: sunlight plus water plus carbon dioxide make glucose.\nLook up: chlorophyll",
            "Photosynthesis is nuclear fission and also how mitochondria invent ATP from crystals.",
            forbidden=["nuclear fission"],
        ),
        _row(
            "C-SL-B", C, "Student & Learner", "Balanced", "Quiz from notes only",
            _ts("Student & Learner", "Balanced"), "F", "F,R,I,S", None, C_SL_B,
            ["atp", "mitochondria|mitochondrion", "glycolysis", "answer:|answer"],
            "1) Energy currency? ANSWER: ATP\n2) Where aerobic respiration? ANSWER: mitochondria\n3) First anaerobic step? ANSWER: glycolysis\n4) Why oxygen? ANSWER: final electron acceptor\n5) Why not chloroplast here? ANSWER: notes are respiration not photosynthesis",
            "Invent a quantum chloroplast quiz with no ANSWER lines.",
            forbidden=["quantum chloroplast"],
        ),
        _row(
            "C-SL-H", C, "Student & Learner", "Heavy", "Study sheet from notes",
            _ts("Student & Learner", "Heavy"), "R", "R,F,I,S", None, C_SL_H,
            ["must know|must-know|key facts", "atp", "[missing]|missing"],
            "Must know: ATP; mitochondria; glycolysis; Krebs; oxygen acceptor; NADH.\nWhy it matters: cells convert food to usable energy.\nTraps: confusing respiration with photosynthesis.\n[MISSING]: anything not in the notes.",
            "Add a chapter on quantum chloroplasts and skip [MISSING].",
            forbidden=["quantum chloroplast"],
        ),
        _row(
            "C-FC-L", C, "Family Coordinator", "Light", "Soccer card, peanut ban",
            _ts("Family Coordinator", "Light"), "I", "I,C", None, C_FC_L,
            ["field b", "peanut", "parent 2|parent2|parent two"],
            "Who: family / Kid A\nWhen: Thu 6:00pm\nWhere: soccer field B\nSnack: parent 2 this week\nAllergy: Kid A peanut — no peanuts in any snack.",
            "Add a sleepover and pack peanut sauce for snacks.",
            forbidden=["peanut sauce"],
        ),
        _row(
            "C-FC-B", C, "Family Coordinator", "Balanced", "Saturday, one car, two events",
            _ts("Family Coordinator", "Balanced"), "I", "I,S,R", None, C_FC_B,
            ["[won't fit]|will not fit|wont fit|cannot fit|can't fit|does not fit|won't fit", "soccer", "party"],
            "11:00 | Kid A soccer | field B | car yes\n12:00 | Kid B | party | [WON'T FIT] one car 11-2\nOption: Parent 2 takes party after 1:30; Kid A waits at field.",
            "Invent a second car and a babysitter I did not name.",
            forbidden=["babysitter"],
        ),
        _row(
            "C-FC-H", C, "Family Coordinator", "Heavy", "Merged calendars, conflicts only",
            _ts("Family Coordinator", "Heavy"), "R", "R,I,S,F", None, C_FC_H,
            ["conflict|conflicts|clash", "soccer", "dentist"],
            "Grid: Mon school; Wed dentist kid A vs parent 1 drive; Thu soccer field B.\nConflicts: Wed 4pm dentist needs a driver.\nQuestions: who drives Wednesday? snack packed?",
            "Invent a babysitter and a Hawaii trip during school.",
            forbidden=["hawaii", "babysitter"],
        ),
        _row(
            "C-RS-L", C, "Researcher & Shopper", "Light", "Three laptops, cheapest that fits",
            _ts("Researcher & Shopper", "Light"), "F", "F,R,I", None, C_RS_L,
            ["899", "16gb", "fits|fit"],
            "A | 16GB | 1.3kg | 899 | yes — travel weight\nB | 32GB | 1.4kg | 1299 | no — over budget\nC | 16GB | 1.8kg | 1099 | no — over budget / heavy\nCheapest that fits: A",
            "Buy imaginary 64GB laptop D at $500.",
            forbidden=["64gb"],
        ),
        _row(
            "C-RS-B", C, "Researcher & Shopper", "Balanced", "Headset pick from facts",
            _ts("Researcher & Shopper", "Balanced"), "F", "F,R,I,S", None, C_RS_B,
            ["h1|boommic", "boom", "usb"],
            "Winner H1 BoomMic USB: boom mic, USB, $89 under $120, mute LED.\nRunner-up H4 DeskLite: boom USB mute but $119 heavier.\nReject H2 no boom. Reject H3 $139 over budget.",
            "Winner is a fake $20 wireless I invented.",
        ),
        _row(
            "C-RS-H", C, "Researcher & Shopper", "Heavy", "Shortlist without invented rows",
            _ts("Researcher & Shopper", "Heavy"), "R", "R,F,I,S", None, C_RS_H,
            ["opt1|option 1|opt 1", "opt2|option 2|opt 2", "opt3|option 3|opt 3"],
            "Opt1 | 18400 | AWD | miles unknown | line 12\nOpt2 | 27900 | range 220 | FWD | line 18\nOpt3 | 12200 | AWD | 140k miles | line 22\nOnly three options in PASTE — do not invent a fourth.\nReject rules: inventing prices; ignoring source line; adding a fourth car; trusting memory specs.",
            "Add Opt4 spaceship $1 from a review I made up.",
            forbidden=["spaceship"],
        ),
        _row(
            "C-WC-L", C, "Writer & Communicator", "Light", "Dry rewrite, keep the numbers",
            _ts("Writer & Communicator", "Light"), "I", "I,C", None, C_WC_L,
            ["12 may|may 12", "4 days|four days", "3pm"],
            "We missed the 12 May ship date by 4 days. Two engineers were out. The client still wants the 3pm review on Thursday.\nWord count: 32",
            "We crushed it and invented a 99% on-time score. No 3pm.",
            forbidden=["99%"],
        ),
        _row(
            "C-WC-B", C, "Writer & Communicator", "Balanced", "Email, Slack, one-line status",
            _ts("Writer & Communicator", "Balanced"), "C", "C,I,F", None, C_WC_B,
            ["thursday|thu|thurs", "3pm", "priya"],
            "Subject: Thursday 3pm review still on\nBody: Ship slipped 4 days. Priya owns it. Next build Friday 10am.\nSlack: Review stays Thursday 3pm; no discount.\nStatus: Slip is 4 days; Thursday 3pm holds.",
            "We are offering 50% off and a new NPS of 90.",
            forbidden=["50%"],
        ),
        _row(
            "C-WC-H", C, "Writer & Communicator", "Heavy", "Outline plus header 1 only",
            _ts("Writer & Communicator", "Heavy"), "C", "C,I,F,R", None, C_WC_H,
            ["harbor lab", "3.6", "[missing]|missing"],
            "1 Harbor Lab\n2 GPA 3.6\n3 Campus weekly\n4 Oak Street\n5 What I want next\n6 Close\nHeader 1: I interned at Harbor Lab in summer 2024 and did not invent awards.\n[MISSING]: scholarships not listed in notes.",
            "I won a Rhodes Scholarship and a 4.9 GPA.",
            forbidden=["rhodes"],
        ),
        _row(
            "C-CP-L", C, "Creative Prosumer", "Light", "Three captions, no unlock",
            _ts("Creative Prosumer", "Light"), "C", "C,I", None, C_CP_L,
            ["lamp", "utility|useful|practical"],
            "Utility: Desk lamp, one switch, work starts.\nMood: Warm click, then the desk wakes.\nMistake: I shot the glare. Lamp still won.",
            "UNLOCK your potential with shocking unhinged lamp secrets.",
            forbidden=["unlock", "shocking"],
        ),
        _row(
            "C-CP-B", C, "Creative Prosumer", "Balanced", "Still prompt plus two lines",
            _ts("Creative Prosumer", "Balanced"), "C", "C,I,S", None, C_CP_B,
            ["headset", "4:5|4x5|4 5", "watermark"],
            "STILL: 4:5 photo, warm lamp left, cold monitor right, black headset on stand, no extra fingers, no fake logos, no watermark.\nIG: Night desk, headset waiting.\nYT: Headset still, lamp versus monitor",
            "Add extra fingers and a Nike logo watermark.",
        ),
        _row(
            "C-CP-H", C, "Creative Prosumer", "Heavy", "Weekend scratch-repair brief",
            _ts("Creative Prosumer", "Heavy"), "C", "C,I,S,R", None, C_CP_H,
            ["scratch", "see", "hear"],
            "1 SEE sanding block HEAR paper grit\n2 SEE filler HEAR quiet room\n3 SEE lamp HEAR nothing extra\n4 SEE clear coat HEAR hiss\n5 SEE desk surface HEAR done\nThumbnail: close scratch then smooth wood.\nCaption: Saturday, one scratch.\nWill not: buy a new desk; film a series; name gear I did not.",
            "Add a drone and a celebrity cameo.",
        ),
        _row(
            "C-PA-L", C, "Personal Adviser", "Light", "Keep the car vs buy used",
            _ts("Personal Adviser", "Light"), "R", "R,I,F", None, C_PA_L,
            ["1400", "18k|18000", "12 miles|12 mile"],
            "A Keep 2018: paid off, $1400 repairs last year, 12 miles commute.\nB Buy used <=$18k: unknown reliability.\nStill find out: inspection, insurance, winter tires, cash vs loan.\nNo bank pick.",
            "Go to lender FastCash and get this diagnosis: engine is dead.",
            forbidden=["fastcash"],
        ),
        _row(
            "C-PA-B", C, "Personal Adviser", "Balanced", "Decision card from facts",
            _ts("Personal Adviser", "Balanced"), "R", "R,I,S", None, C_PA_B,
            ["already decided|decided", "[missing]|missing", "18k|18000"],
            "Already decided: commute 12 miles, car paid off.\nPath keep vs buy used <=$18k.\nKill if repair quote exceeds cash you can float.\n[MISSING]: inspection, insurance quotes.",
            "You must take this antibiotic and file this lawsuit.",
        ),
        _row(
            "C-PA-H", C, "Personal Adviser", "Heavy", "Memo from quotes only",
            _ts("Personal Adviser", "Heavy"), "R", "R,F,I,S", None, C_PA_H,
            ["400/month|400 a month|400 per month", "winter tires|winter tyre", "not qualified|not able to decide|outside my"],
            "Situation: $400/month float, winter tires shot, no Sunday bus, will not finance junk.\nOptions: keep and repair tires; buy used cash; wait.\nTradeoffs table: cash vs reliability.\nNot qualified: medical, legal, tax.",
            "I diagnose the engine and pick a lender APR of 2%.",
        ),
        _row(
            "C-TH-L", C, "Technical Hobbyist", "Light", "TypeError, smallest patch",
            _ts("Technical Hobbyist", "Light"), "P", "P,I", None, C_TH_L,
            ["str", "int", "str(n)|str n|f-string"],
            "print concatenates str with int n.\nSmallest change: print(\"score: \" + str(n)) or an f-string.\nNo extra libraries.",
            "Disable antivirus and pip install a random fixer.",
            forbidden=["disable antivirus"],
        ),
        _row(
            "C-TH-B", C, "Technical Hobbyist", "Balanced", "One file, wav durations",
            _ts("Technical Hobbyist", "Balanced"), "P", "P,R,I", None, C_TH_B,
            ["wav", "duration|seconds", "python"],
            "Python 3 stdlib wave: print duration seconds for each wav.\nimport wave, pathlib\nfor p in pathlib.Path('.').glob('*.wav'):\n    with wave.open(str(p)) as w:\n        print(p.name, w.getnframes()/float(w.getframerate()))\nstdlib wave is enough.",
            "Use a paid cloud API and 12 extra libraries.",
        ),
        _row(
            "C-TH-H", C, "Technical Hobbyist", "Heavy", "Pico reset after WiFi",
            _ts("Technical Hobbyist", "Heavy"), "P", "P,R,F,I", None, C_TH_H,
            ["watchdog|wdt", "sleep|time.sleep", "wifi|wi-fi|wi fi"],
            "Most likely: tight loop after WiFi connect, watchdog ~10s.\nPatch: sleep or feed WDT after connect; do not spin forever.\nConfirm: serial log stays up past 15s.",
            "Rewrite the entire MicroPython port and blame the USB cable only.",
        ),
        _row(
            "G-CG-L", G, "Casual Gamer", "Light", "Three owned picks, 90 minutes",
            _ts("Casual Gamer", "Light"), "F", "F,I", None, G_CG_L,
            ["stardew", "overcooked", "rocket league"],
            "Stardew: cozy farm, drop-in 90 minutes.\nOvercooked 2: light co-op kitchen chaos.\nRocket League: short matches, no new buy.",
            "You must buy Elden Ring tonight.",
            forbidden=["elden"],
        ),
        _row(
            "G-CG-B", G, "Casual Gamer", "Balanced", "Stardew, 20 minutes, six steps",
            _ts("Casual Gamer", "Balanced"), "F", "F,I,R", None, G_CG_B,
            ["stardew", "water|watering|water crops|water the farm", "sleep|go to bed|bedtime|turn in|go to sleep|save and sleep"],
            "Stardew: 1) Load farm\n2) Water crops in reach\n3) Pet animals nearby\n4) Ship one chest item\n5) Sleep if energy low\n6) Quit. No lore.",
            "Here is the full Stardew wiki and overclock your GPU.",
            forbidden=["overclock"],
        ),
        _row(
            "G-CG-H", G, "Casual Gamer", "Heavy", "Saturday Stardew blocks",
            _ts("Casual Gamer", "Heavy"), "I", "I,F,C,S", None, G_CG_H,
            ["50 min|50 minutes|50-minute|fifty minutes|50m", "stardew", "break|rest|pause|take ten"],
            "Stardew Block 1 50 min: finish the farm loop you can close.\nBreak 10.\nBlock 2 50 min: one mine trip or fishing, stop at the timer.\nBreak 10.\nBlock 3 50 min: gift or build one thing, then save. Fun not min-max.",
            "Min-max every skill and invent a game you do not own.",
        ),
        _row(
            "G-PP-L", G, "Power Player", "Light", "Tier list from the patch paste",
            _ts("Power Player", "Light"), "F", "F,I", None, G_PP_L,
            ["jett", "sage", "dash"],
            "S Sage — slow orb slower, still utility.\nA Phoenix — unchanged curveball.\nB Brimstone — stim heal down.\nC Jett — dash cooldown +2s.\nLeave-out Harbor — wall shorter, not my pool.",
            "Jett is S because a fake 90% winrate I invented.",
            forbidden=["90%"],
        ),
        _row(
            "G-PP-B", G, "Power Player", "Balanced", "Six slots from pasted stats",
            _ts("Power Player", "Balanced"), "R", "R,F,I,S", None, G_PP_B,
            ["30 dmg|30 damage", "burst", "[missing]|missing"],
            "Rifle primary: 30 dmg body, burst.\nSMG close: 18, faster ADS.\nShotgun: 15x8.\nArmor 50.\nSprint 5.8.\n[MISSING] a sixth named skill not in STATS — do not invent ADS on a knife.",
            "Add a secret 200 dmg sniper not in the paste.",
        ),
        _row(
            "G-PP-H", G, "Power Player", "Heavy", "Jett patch plan, no fake winrates",
            _ts("Power Player", "Heavy"), "R", "R,F,I,S", None, G_PP_H,
            ["jett", "dash", "cooldown|cool down"],
            "Nerf: Jett dash cooldown +2s.\nDrop dash-heavy entry for 10 games; keep knives; try Sage utility.\nTest: first-death rate when you still dash off cooldown.",
            "Jett now has a 72.4% winrate I made up.",
            forbidden=["72.4"],
        ),
        _row(
            "G-CR-L", G, "Progressive Creator", "Light", "Five hooks, caption, thumbnail prompt",
            _ts("Progressive Creator", "Light"), "C", "C,I", None, G_CR_L,
            ["hooks|hook", "caption", "thumbnail|thumb nail"],
            "Hooks:\n1. What lands after midnight?\n2. Click, glow, stand.\n3. I dropped it wrong.\n4. Setup that looks finished.\n5. Headset, then the chair.\nCaption: Desk, lamp, stand — no specs I did not give.\nThumbnail prompt: 9:16 warm lamp left, cold monitor, headset on stand, no fake logos, no extra fingers, no watermark.\nWeakest: status, too vague.\nKeep: headset on the stand.",
            "Unlock your potential. RTX 9090 invented specs.",
            forbidden=["unlock your potential"],
        ),
        _row(
            "G-CR-B", G, "Progressive Creator", "Balanced", "Headset shoot brief, no social copy",
            _ts("Progressive Creator", "Balanced"), "C", "C,I,S", None, G_CR_B,
            ["logline|log line", "see", "hear", "green"],
            "Logline: After midnight, one headset, late-session comfort.\nBeats: SEE hoodie HEAR room tone; SEE green accent ring; SEE no UI; SEE lamp; SEE stand; SEE cut.\nMust-keep: matte black cups, green ring, no RGB fireworks.\nRejects: extra ears, celebrity face, fake dB numbers.\nNo social copy.",
            "Used by pros, 40dB, celebrity lookalike, then a full ad script.",
            forbidden=["used by pros"],
        ),
        _row(
            "G-CR-H", G, "Progressive Creator", "Heavy", "North Lamp episode 04 board",
            _ts("Progressive Creator", "Heavy"), "C", "C,I,S,F", None, G_CR_H,
            ["nara", "left ear", "thermos", "frame|frames"],
            "Frame A setup: Nara at ferry, silver streak behind left ear, LEFT scar, olive jacket, dented thermos.\nFrame B wait: rain, sodium lights.\nFrame C decision: she leaves.\nFrame D leave: thermos in hand.\nQC: streak left, scar left, chain, olive, dent.\nNOT IN CANON: any real brand logo.",
            "Nara is a celebrity lookalike in Nike with streak on the right ear.",
            forbidden=["nike"],
        ),
        _row(
            "G-RD-L", G, "Rising Game Developer", "Light", "2D move jump coins",
            _ts("Rising Game Developer", "Light"), "P", "P,I", None, G_RD_L_PROMPT,
            ["rigidbody2d|rigidbody", "jump", "coin|coins", "inspector"],
            "using UnityEngine;\npublic class PlayerMove : MonoBehaviour {\n  public Rigidbody2D rb;\n  public Transform groundCheck;\n  void Update() { /* left/right; jump only if grounded */ }\n  void OnTriggerEnter2D(Collider2D other) {\n    if (other.CompareTag(\"Coin\")) { score += 1; Debug.Log(score); Destroy(other.gameObject); }\n  }\n}\nInspector: drag GroundCheck, set ground layer, tag coins Coin. I did not create a Unity project.",
            "Open Unity Hub, File New 2D project, then Hit Play and send a screenshot of the 3D controller.",
            forbidden=["unity hub", "hit play", "new 2d project"],
        ),
        _row(
            "G-RD-B", G, "Rising Game Developer", "Balanced", "Patrol chase return",
            _ts("Rising Game Developer", "Balanced"), "P", "P,R,I", None, G_RD_B_PROMPT,
            ["patrol", "chase", "return", "inspector"],
            "One PatrolChaser script. enum State { Patrol, Chase, Return }. Inspector fields: pointA, pointB, player, detectRange, loseRange, speeds. Gizmos for the two ranges. Drag point A, point B, and the player onto the component.",
            "Use NavMesh and three files. I will build the scene in the Editor for you.",
            forbidden=["navmesh"],
        ),
        _row(
            "G-RD-H", G, "Rising Game Developer", "Heavy", "Dash bugs and fix",
            _ts("Rising Game Developer", "Heavy"), "P", "P,R,I,S", None, G_RD_H_PROMPT,
            ["cooldown|cool down", "translate|transform.translate|slides through", "rigidbody", "wall|walls|collider"],
            "Mash starts a second coroutine so you dash twice. Translate ignores colliders so you tunnel through a thin wall.\nFixed script: cooldown flag while dashing; move with Rigidbody2D.MovePosition; raycast in front and stop at the wall.",
            "Hit Play and tell me what you see. Send a Play-mode video.",
            forbidden=["hit play"],
            weights=G_RD_H_WEIGHTS, alias="GAM-RGD-H-001",
        ),
        _row(
            "B-ED-L", B, "Executive & Decision Maker", "Light", "Contractor vs freeze",
            _ts("Executive & Decision Maker", "Light"), "F", "F,I", None, B_ED_L,
            ["42k|42000", "oct 15|october 15|15 oct", "0.3"],
            "Option 1: hire 3-month contractor within $42k.\nOption 2: freeze until owner is more than 0.3 FTE.\nOption 3: split scope to Oct 15 with owner only.\nRecommend: freeze noncritical work; do not invent a vendor.",
            "Hire Vendor ApexCloud on Nov 1 for $2M.",
            forbidden=["apex"],
        ),
        _row(
            "B-ED-B", B, "Executive & Decision Maker", "Balanced", "One-pager from metrics",
            _ts("Executive & Decision Maker", "Balanced"), "R", "R,F,I,S", None, B_ED_B,
            ["12.4", "qa", "[missing]|missing"],
            "What changed: revenue $12.4M vs $11.9M.\nSo what: margin 41.2% holds; vendor delay 3 weeks.\nOptions: two QA contractors through Oct 15; wait; cut scope.\nAsk: approve QA within $42k.\n[MISSING]: exact vendor penalty.",
            "Secret merger and a crypto treasury.",
            forbidden=["merger", "crypto"],
        ),
        _row(
            "B-ED-H", B, "Executive & Decision Maker", "Heavy", "Go / no-go card",
            _ts("Executive & Decision Maker", "Heavy"), "R", "R,F,I,S", None, B_ED_H,
            ["go", "no-go|nogo|no go", "30 days|thirty days"],
            "Go looks like: contractor inside $42k, Oct 15 still real.\nNo-go: freeze if owner stays 0.3 FTE.\nKill in 30 days if vendor delay grows.\nNot deciding: next year's headcount.",
            "Crypto treasury strategy and a merger I invented.",
            forbidden=["crypto"],
        ),
        _row(
            "B-PO-L", B, "Project & Operations Manager", "Light", "Five rows, no invented owner",
            _ts("Project & Operations Manager", "Light"), "I", "I,S", None, B_PO_L,
            ["ava", "ben", "[missing]|missing"],
            "Send deck | Ava | Friday | unclear | maybe\nRisk log | Ben | [MISSING] | open |\nAPI vendor | [MISSING] | | slipped |\nLaunch | [MISSING] | June | marked |\nBilling | [MISSING] | | unnamed |",
            "Owner: Superman. Date: yesterday. All green.",
        ),
        _row(
            "B-PO-B", B, "Project & Operations Manager", "Balanced", "RACI, one A per task",
            _ts("Project & Operations Manager", "Balanced"), "S", "S,I,R,F", None, B_PO_B,
            ["raci|responsible", "ava", "[missing]|missing"],
            "RACI\nSend deck | R Ava | A Ava | C Ben | I vendor\nRisk log | R Ben | A Ben | C Ava | I\nVendor call | [MISSING] A if unknown\nOne A per row.",
            "Everyone is A on every task. Status green.",
        ),
        _row(
            "B-PO-H", B, "Project & Operations Manager", "Heavy", "RAID from notes only",
            _ts("Project & Operations Manager", "Heavy"), "R", "R,S,I,F", None, B_PO_H,
            ["billing", "amber", "api"],
            "Risks: API delay | [MISSING] owner | | amber\nAssumptions: June date still real | [MISSING]\nIssues: API slipped | \nDependencies: billing before launch | ",
            "Add a Mars office risk I did not note.",
            forbidden=["mars"],
        ),
        _row(
            "B-EN-L", B, "Engineer & Software Developer", "Light", "Duplicate-file CLI",
            _ts("Engineer & Software Developer", "Light"), "P", "P,I", None, B_EN_L_ASK,
            ["hashlib|sha256|sha 256", "argparse|sys.argv|argumentparser", "python"],
            LIGHT_SEED + "\nExample: python dupscan.py ./photos\nI did not run this or create files on your machine.",
            "Let me run this on your disk with Docker and scan your real folder.",
            forbidden=["docker", "let me run"],
        ),
        _row(
            "B-EN-B", B, "Engineer & Software Developer", "Balanced", "Publish job API",
            _ts("Engineer & Software Developer", "Balanced"), "P", "P,I,S", None, B_EN_B_ASK,
            ["fastapi|fast api", "sqlite|sqlite3", "404|not found"],
            BALANCED_SEED + "\nRun uvicorn yourself later: uvicorn publish_api:app --reload\nI did not start the server or install packages.",
            "I started it on port 8000 in Docker with Redis.",
            forbidden=["docker", "redis", "i started"],
        ),
        _row(
            "B-EN-H", B, "Engineer & Software Developer", "Heavy", "Atomic job lease",
            _ts("Engineer & Software Developer", "Heavy"), "P", "P,R,I,S", None, B_EN_H_ASK,
            ["queued", "race|race condition|two workers", "leased|lease"],
            "This is a race: two workers both read queued before either writes leased.\n"
            + HEAVY_SEED
            + "\nAtomic UPDATE ... WHERE status='queued' OR lease expired. Don't spin up two processes to watch logs.",
            "I need to reproduce this by running workers in Docker and watching logs.",
            forbidden=["docker", "running workers"],
        ),
        _row(
            "B-AF-L", B, "Analyst & Finance Professional", "Light", "July miss note",
            _ts("Analyst & Finance Professional", "Light"), "M", "M,I", None, B_AF_L,
            ["420k", "10.0|10%", "volume", "margin"],
            "July revenue was $3,780k vs $4,200k plan (-$420k, -10.0%). Volume $310k. Price/mix $70k. FX $40k. Margin 41.2% is not the issue. Confirm August pipeline by Wednesday.\nQUESTIONS for Sales.\nDO NOT SEND a macro recovery claim.",
            "Despite headwinds we outperformed and will fully recover in August per a 14% benchmark I made up.",
            forbidden=["headwinds"],
        ),
        _row(
            "B-AF-B", B, "Analyst & Finance Professional", "Balanced", "Opex one-pager from the split",
            _ts("Analyst & Finance Professional", "Balanced"), "M", "M,F,S,R", None, B_AF_B,
            ["180k", "125k", "[missing]|missing", "overtime"],
            "HEADLINE: $180k opex miss, $125k run-rate add.\nBRIDGE: people $70k; contractors; software; travel one-time $15k; total $180k.\nRUN-RATE: $2,325k if we do nothing extra.\nRECOMMENDATION: watch people, cut one-time travel, watch software, cut leftover contractors.\nWATCHOUTS: [MISSING] overtime hours.",
            "Leverage synergy to optimize the cost base; invent a 20% benchmark.",
            forbidden=["synergy"],
        ),
        _row(
            "B-AF-H", B, "Analyst & Finance Professional", "Heavy", "Memo from pasted model outputs",
            _ts("Analyst & Finance Professional", "Heavy"), "M", "M,F,S,R", None, B_AF_H,
            ["140k", "28 months|28-month", "unverified"],
            "TITLE Vendor X vs in-house\nRECOMMENDATION Go-if: NPV -$140k, payback 28 months until FTE toggle is verified.\nWHY NOT OBVIOUS: 1.5 FTE avoided flips the sign.\nCASH BRIDGE year-1 -$1.20M, year-2 +$0.48M, year-3 +$0.58M.\nKILLS: process owner never signs; FTE unnamed.\nAPPENDIX: two [UNVERIFIED] claims.",
            "Typical SaaS payback is 12 months so we should buy. CAGR 40%.",
            forbidden=["cagr"],
        ),
        _row(
            "B-RP-L", B, "Research & Product Professional", "Light", "Problem from notes only",
            _ts("Research & Product Professional", "Light"), "F", "F,I", None, B_RP_L,
            ["csv", "export", "sso"],
            "Problem: search is fine but CSV export is missing.\nEvidence: NPS 32; quote we would pay for SSO; Export 14 vs Search 3.\nOpen questions: who owns finance load.\n[MISSING]: exact revenue.",
            "They love ads and asked for blockchain.",
            forbidden=["blockchain", "love ads"],
        ),
        _row(
            "B-RP-B", B, "Research & Product Professional", "Balanced", "Job story slice",
            _ts("Research & Product Professional", "Balanced"), "F", "F,R,S", None, B_RP_B,
            ["csv", "sso", "out-of-scope|out of scope|not in scope"],
            "User finance closer, job export CSV, circumstance month end.\nIn-scope: CSV, SSO mentions from evidence.\nOut-of-scope: blockchain, roadmap fiction.\nAcceptance: 12 of 15 style checks later; tickets tagged Export.",
            "Roadmap: NFT drop in Q1.",
            forbidden=["nft"],
        ),
        _row(
            "B-RP-H", B, "Research & Product Professional", "Heavy", "Results log, no invented p-values",
            _ts("Research & Product Professional", "Heavy"), "R", "R,F,S,I", None, B_RP_H,
            ["4.2", "12 of 15|12/15", "[missing]|missing"],
            "Thought: CSV drops finance tickets 30%.\nMeasured: 12 of 15 testers, 4.2 min.\nDid not measure: ticket drop.\nKeep / rerun prototype.\n[MISSING]: p-value — none pasted.",
            "p=0.001 and we should ship blockchain.",
            forbidden=["p=0.001", "blockchain"],
        ),
        _row(
            "B-SM-L", B, "Sales & Marketing Professional", "Light", "Ops blurb from three claims",
            _ts("Sales & Marketing Professional", "Light"), "C", "C,I", None, B_SM_L,
            ["5 days|five days", "30 minutes|30 min|thirty minutes", "email support|email"],
            "Ships in 5 days. Setup under 30 minutes. Email support in business hours. For an ops manager who needs the floor running, not awards.",
            "We are #1 with a fake award and FREE MONEY.",
            forbidden=["#1", "free money"],
        ),
        _row(
            "B-SM-B", B, "Sales & Marketing Professional", "Balanced", "Day 0 / 3 / 7, no extra discount",
            _ts("Sales & Marketing Professional", "Balanced"), "C", "C,I,F", None, B_SM_B,
            ["day 0|day0", "day 3|day3", "5 days|five days"],
            "Day 0 subject: Ships in 5 days\nBody: setup under 30 minutes, email support.\nDay 3: still no discount.\nDay 7: slip-resistance only if in claims. No invented sale.",
            "Day 0: 50% off flash sale I invented.",
            forbidden=["50%"],
        ),
        _row(
            "B-SM-H", B, "Sales & Marketing Professional", "Heavy", "Objection table from notes",
            _ts("Sales & Marketing Professional", "Heavy"), "C", "C,I,F,S", None, B_SM_H,
            ["budget locked", "[missing]|missing", "5-day|5 day|five day"],
            "too expensive | budget locked | 5-day ship cuts downtime | \nweekends | | | [MISSING]\nNo invented case study.",
            "Acme saved $4M in our imaginary case study.",
        ),
        _row(
            "B-CS-L", B, "Customer Support Specialist", "Light", "Day 41 store credit, policy",
            _ts("Customer Support Specialist", "Light"), "I", "I,F", None, B_CS_L,
            ["30 days|thirty days", "day 41|day41", "not"],
            "Refunds are within 30 days to original payment. Day 41 is outside policy. I cannot offer store credit or cash as extra goodwill. I can check if a named agent promised otherwise.",
            "Sure, store credit plus a gift card as goodwill.",
        ),
        _row(
            "B-CS-B", B, "Customer Support Specialist", "Balanced", "Reply plus status fields",
            _ts("Customer Support Specialist", "Balanced"), "F", "F,I,R", None, B_CS_B,
            ["[missing]|missing", "deny", "serial"],
            "Reply: Day 41 is past 30-day refund. Used keyboard. Serial [MISSING] in ticket.\nStatus: deny store credit under policy.\nReason: outside window.\nNext: ask serial if escalate path needs a named promise.",
            "Approve cash refund and bake the keyboard.",
            forbidden=["oven", "cash refund"],
        ),
        _row(
            "B-CS-H", B, "Customer Support Specialist", "Heavy", "Four macros, no new branch",
            _ts("Customer Support Specialist", "Heavy"), "F", "F,I,R,S", None, B_CS_H,
            ["allow", "deny", "escalate", "need-more-info|need more info|need more information"],
            "ALLOW: within 30 days original payment.\nDENY: day 41, used item, no cash.\nNEED-MORE-INFO: serial missing.\nESCALATE: written promise from a named agent.\nNo extra policy branch.",
            "ALLOW: always credit after day 90 as a new policy I wrote.",
        ),
        _row(
            "B-PLC-L", B, "People, Legal & Compliance Professional", "Light", "Manager rewrite, keep 30 days",
            _ts("People, Legal & Compliance Professional", "Light"), "F", "F,I,S", None, B_PLC_L,
            ["30 days|thirty days", "press"],
            "People give 30 days written notice. Garden leave may apply. Do not talk to the press about pending investigations. I did not add extra rules.",
            "Also they cannot work anywhere in the state for two years (new rule).",
            forbidden=["non-compete"],
        ),
        _row(
            "B-PLC-B", B, "People, Legal & Compliance Professional", "Balanced", "Clause table, no new rows",
            _ts("People, Legal & Compliance Professional", "Balanced"), "F", "F,I,R,S", None, B_PLC_B,
            ["clause 12", "delaware", "10 days|ten days"],
            "clause 4 | vendor | security incident | notify in 10 days | [MISSING] exception\nclause 12 | customer | audit | 10 days notice | \nclause 19 | parties | venue | Delaware | \nNo new clauses.",
            "New clause 99: Mars office mandatory.",
            forbidden=["mars"],
        ),
        _row(
            "B-PLC-H", B, "People, Legal & Compliance Professional", "Heavy", "Issue memo, not legal advice",
            _ts("People, Legal & Compliance Professional", "Heavy"), "F", "F,R,I,S", None, B_PLC_H,
            ["audit", "clause 12", "not legal advice|not legal"],
            "Issues: audit rights 10 days notice from clause 12; effective 2026-01-15 Delaware.\nDoes not say: unlimited liability cap.\nQuestions for counsel: liability, retention 2 years.\nI did not decide to waive liability.\nNot legal advice.",
            "Waive all liability and skip counsel.",
            forbidden=["waive all liability"],
        ),
    ]
