import type { LucideIcon } from "lucide-react";
import {
  Activity,
  AlertTriangle,
  ArrowLeft,
  ArrowRight,
  Ban,
  BookOpen,
  Box,
  Boxes,
  Brain,
  Briefcase,
  Calculator,
  Camera,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronRight,
  Columns2,
  CircuitBoard,
  CircleCheck,
  Clapperboard,
  Code2,
  Cpu,
  Download,
  ExternalLink,
  Flag,
  Folder,
  FolderOpen,
  Gamepad2,
  Gauge,
  GraduationCap,
  HardDrive,
  Headphones,
  Heart,
  House,
  Kanban,
  Landmark,
  LifeBuoy,
  Lightbulb,
  ListChecks,
  Loader,
  Megaphone,
  MemoryStick,
  Microscope,
  Network,
  Pause,
  PenLine,
  Play,
  RefreshCw,
  Scale,
  ScrollText,
  Search,
  Settings,
  Share2,
  ShieldAlert,
  ShieldCheck,
  ShoppingBag,
  Sparkles,
  Square,
  SquareChevronUp,
  Stethoscope,
  Terminal,
  Timer,
  Trash2,
  Trophy,
  UserRound,
  Users,
  Wrench,
  X,
  Zap,
} from "lucide-react";

const ICONS: Record<string, LucideIcon> = {
  activity: Activity,
  "alert-triangle": AlertTriangle,
  "arrow-left": ArrowLeft,
  "arrow-right": ArrowRight,
  ban: Ban,
  "book-open": BookOpen,
  box: Box,
  boxes: Boxes,
  brain: Brain,
  briefcase: Briefcase,
  calculator: Calculator,
  camera: Camera,
  check: Check,
  "check-circle-2": CheckCircle2,
  "chevron-down": ChevronDown,
  "chevron-right": ChevronRight,
  "circuit-board": CircuitBoard,
  "circle-check": CircleCheck,
  clapperboard: Clapperboard,
  "code-2": Code2,
  "columns-2": Columns2,
  cpu: Cpu,
  download: Download,
  "external-link": ExternalLink,
  flag: Flag,
  folder: Folder,
  "folder-open": FolderOpen,
  "gamepad-2": Gamepad2,
  gauge: Gauge,
  "graduation-cap": GraduationCap,
  "hard-drive": HardDrive,
  headphones: Headphones,
  heart: Heart,
  house: House,
  kanban: Kanban,
  landmark: Landmark,
  "life-buoy": LifeBuoy,
  lightbulb: Lightbulb,
  "list-checks": ListChecks,
  loader: Loader,
  megaphone: Megaphone,
  "memory-stick": MemoryStick,
  microscope: Microscope,
  network: Network,
  pause: Pause,
  "pen-line": PenLine,
  play: Play,
  "refresh-cw": RefreshCw,
  scale: Scale,
  "scroll-text": ScrollText,
  search: Search,
  settings: Settings,
  share: Share2,
  "shield-alert": ShieldAlert,
  "shield-check": ShieldCheck,
  "shopping-bag": ShoppingBag,
  sparkles: Sparkles,
  square: Square,
  "square-chevron-up": SquareChevronUp,
  stethoscope: Stethoscope,
  terminal: Terminal,
  timer: Timer,
  trash: Trash2,
  trophy: Trophy,
  "user-round": UserRound,
  users: Users,
  wrench: Wrench,
  x: X,
  zap: Zap,
};

type Props = {
  name: string;
  size?: number;
  className?: string;
  style?: React.CSSProperties;
};

export function Icon({ name, size = 16, className, style }: Props) {
  const Cmp = ICONS[name] ?? Box;
  return <Cmp size={size} strokeWidth={2.5} className={className} style={style} aria-hidden />;
}
